#!/usr/bin/env python3
"""
Convert a saved tool-TCP pivot calibration YAML into a fixed joint (flange ->
tool TCP) and write it into a xacro file, so the calibrated TCP becomes part
of the robot description MoveIt/robot_state_publisher actually see.

A static TF publisher (see pivot_publish_node.py / tcp_publish.launch.py) is
not enough on its own: MoveIt's ``arm/set_eelink`` requires the target link to
exist in the URDF/SRDF, not just in the live TF tree. Bake first, then switch
the active end effector.

Typical use after saving a new pivot calibration from the GUI:

    python3 -m hand_eye_calibration.tool_tcp_cli \\
        --update-xacro ~/arms_ws/src/piper_ros/src/robot_description/piper_description/urdf/include/piper_tool_tcp_macros.xacro

then rebuild piper_description, restart the robot stack, and call
arm/set_eelink with the tcp link name to make MoveIt plan to it.
"""

from __future__ import annotations

import argparse
import os
import sys

import numpy as np
import yaml
from scipy.spatial.transform import Rotation as Rot

from .depthai_mount_cli import _rotation_to_urdf_rpy, update_xacro_origin

DEFAULT_JOINT_NAME = "piper_tool_tcp_mount"
DEFAULT_MACRO_NAME = "piper_mount_tool_tcp"


def _load_yaml(path: str) -> dict:
    path = os.path.expanduser(path)
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _default_xacro_content(
    macro_name: str, joint_name: str, tcp_link: str,
    xyz: np.ndarray, rpy: tuple[float, float, float],
) -> str:
    return (
        '<?xml version="1.0"?>\n'
        "<!--\n"
        f"  Piper tool TCP mount, generated by tool_tcp_cli from a pivot calibration.\n"
        "  Regenerate after re-calibrating with:\n"
        f"    python3 -m hand_eye_calibration.tool_tcp_cli --update-xacro path/to/this/file.xacro\n"
        "-->\n"
        f'<robot xmlns:xacro="http://ros.org/wiki/xacro" name="{macro_name}_defs">\n\n'
        f'  <xacro:macro name="{macro_name}" params="parent_link">\n'
        f'    <link name="{tcp_link}"/>\n'
        f'    <joint name="{joint_name}" type="fixed">\n'
        f'      <origin\n'
        f'        xyz="{xyz[0]:.12f} {xyz[1]:.12f} {xyz[2]:.12f}"\n'
        f'        rpy="{rpy[0]:.12f} {rpy[1]:.12f} {rpy[2]:.12f}"/>\n'
        f'      <parent link="${{parent_link}}"/>\n'
        f'      <child link="{tcp_link}"/>\n'
        f"    </joint>\n"
        f"  </xacro:macro>\n"
        f"</robot>\n"
    )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "calibration_yaml",
        nargs="?",
        default=os.path.expanduser("~/.ros/tool_tcp_calibration.yaml"),
        help="Path to tool_tcp_calibration YAML (default: ~/.ros/tool_tcp_calibration.yaml)",
    )
    p.add_argument(
        "--update-xacro",
        metavar="XACRO_PATH",
        help=(
            "Write/rewrite the mount joint <origin> in this xacro file. "
            "Creates the file with a fresh macro if it doesn't exist yet."
        ),
    )
    p.add_argument(
        "--joint-name",
        default=DEFAULT_JOINT_NAME,
        help=f"Mount joint name inside the xacro (default: {DEFAULT_JOINT_NAME})",
    )
    p.add_argument(
        "--macro-name",
        default=DEFAULT_MACRO_NAME,
        help=f"xacro:macro name to create if the file doesn't exist yet (default: {DEFAULT_MACRO_NAME})",
    )
    args = p.parse_args(argv)

    data = _load_yaml(args.calibration_yaml)
    t = data["transform"]
    flange = data.get("robot_flange_frame", data.get("parent_frame", "link6"))
    tcp_link = data.get("tcp_name", "tool_tcp")

    xyz = np.array([t["tx"], t["ty"], t["tz"]], dtype=float)
    rot = Rot.from_quat([t["qx"], t["qy"], t["qz"], t["qw"]]).as_matrix()
    rpy = _rotation_to_urdf_rpy(rot)

    print(f"# Tool TCP mount joint ({flange} -> {tcp_link}):")
    print(f'#   xyz="{xyz[0]:.12f} {xyz[1]:.12f} {xyz[2]:.12f}"')
    print(f'#   rpy="{rpy[0]:.12f} {rpy[1]:.12f} {rpy[2]:.12f}"')
    if t["qx"] == 0.0 and t["qy"] == 0.0 and t["qz"] == 0.0:
        print(
            "# Note: orientation defaults to the flange orientation (pivot calibration "
            "only determines the tip position). Edit the rpy above if you have a "
            "known tool axis / CAD orientation."
        )

    if args.update_xacro:
        path = os.path.expanduser(args.update_xacro)
        if os.path.isfile(path):
            update_xacro_origin(path, xyz, rpy, args.joint_name)
            print(f"# Updated {path} (joint '{args.joint_name}').")
        else:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            content = _default_xacro_content(args.macro_name, args.joint_name, tcp_link, xyz, rpy)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"# Created {path} (macro '{args.macro_name}', joint '{args.joint_name}').")
        print(
            "# Rebuild the description package, restart the robot stack, then call "
            f"arm/set_eelink with '{tcp_link}' to make MoveIt plan to this TCP."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
